---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 751373727946858496-7VvAnoQWzn4rXpIqwhWv6Cohscm4B3H
:access_token_secret: IEdOG4puc2G6fnyUOmuHFp8Bhh5B1t61zyUGIgZg0Q6p0
